### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by ck932** [muquit/mailsend-go#14]
Hi,

My device is raspberry pi 2b+ , os is jessie, I download the mailsend-go_1.0.5_linux-ARM.deb,
After installation " sudo dpkg -i mailsend-go_1.0.5_linux-ARM.deb", I run mailsend, the result is 
"Illegal instruction"
Then, I "sudo dpkg -r mailsend-go" and tar -xf "mailsend-go_1.0.5_linux-ARM.tar.gz"
But the result is "Illegal instruction" again.

What should I do? 

Thanks a lot

**Comment by muquit** [comment]
My 2b+ runs Raspbian stretch. I uploaded a gzip compressed binary mailsend-go-raspberry-pi-jessie.gz. Please gunzip and see if you have any luck. I have no way of testing it. I used the flags ```GOOS=linux GOARCH=arm GOARM=7 go build``` go compile it. If it does not work, you have to research on what should be the proper flags for jessie.
Thanks.
