### ISSUE TITLE
Request Read Receipts

### ISSUE THREAD

**Issue by drdunn858** [muquit/mailsend-go#15]
I see that -rrr is not included in the list of functions.  Is it available, or will it be available in the future?

**Comment by muquit** [comment]
I can add it in the next release.
In the mean time you can add *Disposition-Notification-To* header to achieve the same goal.
```
header -name "Disposition-Notification-To" -value "you@example.com"
```

**Comment by drdunn858** [comment]
Awesome, thank you,

**Comment by pferrucci** [comment]
There was a newer release in December 2020 and I don't see this feature in this version.
Just saying to be sure it wasn't missed.
