### ISSUE TITLE
Send email to multi to adress

### ISSUE THREAD

**Issue by andrewjswan** [muquit/mailsend-go#2]
I try send email to  multi adress
In help i see:
  -t to,to..*            - email address/es of the recipient/s. Required
I try:
mailsend-go.exe -f mail@mail.com -smtp server -t mail1@mail.com,mail2@mail.com -cc mail3@mail.com -sub "Subject" body -msg "Message"
And got error:
**ERROR**: gomail: could not send email 1: gomail: invalid address "mail1@mail.com,mail2@mail.com": mail: expected single address, got ",mail2@mail.com"

**Comment by muquit** [comment]
It's a bug. Will fix soon. Thanks for reporting!

**Comment by muquit** [comment]
Please try v1.0.3.
Thanks.

**Comment by andrewjswan** [comment]
Thanks. Worked!
