### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by bostonbob** [muquit/mailsend-go#21]
Hi, I appreciate too much your job since, mailsend.
Now with this new version I have problems, I trust you can help me to solve them.
1- AVG reveal it like a malware , I switched off him to try mailsend-go.
2- I need mailsend-go for a very simple use. My syntax is:
mailsend-go -smtp mysmtp -from myaddress -to addressOfReciever auth -user myusername  -pass mypass -sub Hello -msg BestRegards .
It doesn t work. 
I'm looking forward your reply.
Thank you so much.

**Comment by muquit** [comment]
The last arg should be `body -msg "message"`
Thanks.

**Comment by bostonbob** [comment]
Thank you for your quickly reply.
I will try to fix this tomorrow morning and I will let u know if it works. Thank u so much !

**Comment by bostonbob** [comment]
I adjust with body -msg, but when I launch, it says : ERROR: dial tcp xx.xxx.xxx.xxx:0: connectex: The requested address is not valid in its context.
What can I do?

**Comment by bostonbob** [comment]
Ok man, I adjust one thing, and now works ! Awesome , thank you very much.
