### ISSUE TITLE
New lines in -msg

### ISSUE THREAD

**Issue by ragimiri** [muquit/mailsend-go#22]
Hi, is it possible to add new lines in -msg? If not, is it possible to implement this?

**Comment by muquit** [comment]
It works fine in Linux/Unix. Example:
```
body -msg 'This is a message.
This is another line.
This is yet another line'
```
`body` command also takes a flag `-file`. For a long message, you can create a temp file from a script and specify the path with `body -file /path/file.txt`

Thanks.

**Comment by ragimiri** [comment]
Unfortunately that does not work on Windows. I was hoping for some special chars support, like \n.

**Comment by muquit** [comment]
ok. I will add this support in the next release. It will be something like:
```
body -msg "This is a message.\nThis is a new line.\nThis is yet another new line"
```
And I will replace \n with real new line. It should work.
