### ISSUE TITLE
Attachment name seems ignored

### ISSUE THREAD

**Issue by mleone87** [muquit/mailsend-go#26]
Hi
I'm trying to send a mail with an attachment but if I specify the name for the attachment, it gets ignored.

I'm using the mailsend-go_v1.0.8_windows-64bit.zip

The command line part is .... attach -name "file.csv" -file LICENSE.txt

The mail that arrive is:

...
Content-Disposition: attachment; filename="LICENSE.txt"
Content-Transfer-Encoding: base64
Content-Type: text/plain; charset=utf-8; name="LICENSE.txt"
....

**Comment by muquit** [comment]
oops! looks like I forgot to implement `-name` option for attachments. Will be in the next release.
Thanks.
