### ISSUE TITLE
Windows Defender remove mailsend-go.exe

### ISSUE THREAD

**Issue by Loris-F** [muquit/mailsend-go#28]
Using mailsend-go on some computer, but now find a problem, maybe a false positive.
When copying the exe file on a computer with Windows Server 2016 Standard.
*Windows Defender delete the exe* , message say it is a virus.
![Immagine 9](https://user-images.githubusercontent.com/63682343/79617908-ef232200-8108-11ea-8872-118b484fd84b.png)

**Comment by muquit** [comment]
Nothing but to say it is stupid. You should contact Windows defender people for false positive. Source is available, you can try to compile it yourself. I don't have access to Windows, the program is cross compiled on a Mac.
Thanks.

**Comment by Loris-F** [comment]
Already signaled to Microsoft. This was intended only for your information. BTW you can delete this.
