### ISSUE TITLE
Password leak through command line

### ISSUE THREAD

**Issue by gaebor** [muquit/mailsend-go#30]
Sender username and password are provided via command line parameters which are visible to other users. See: https://unix.stackexchange.com/questions/298178/hide-arguments-of-commands-in-ps

It would be nice to provide authentication information with a file or something.

**Comment by muquit** [comment]
mailsend-go supports environment variable SMTP_USER_PASS to the password instead of -pass flag.
Thanks.

**Comment by gaebor** [comment]
But environment variables are also exposed to non-root users under `/proc/<pid>/environ`

**Comment by muquit** [comment]
Environments are exposed for all users in /proc/pid/environ but can be accessed if a user has read permission to it. root can access it for any user of course. There is no escape from root. Question is where to draw the line? I can probably add an option to read from stdin in future release.
Thanks.

**Comment by gaebor** [comment]
Thx, I forgot that. This should work.
