### ISSUE TITLE
Return-Path support

### ISSUE THREAD

**Issue by RNalivaika** [muquit/mailsend-go#31]
Hi, does mailsend-go support specifying custom Return-Path address?
Thanks

**Comment by muquit** [comment]
Any custom header can be set with header command. However Return-Path is not one of those headers. It will be over-written by smtp server from *From* address. If you want to change say, *Reply-To* header, the option is:
<pre>
header -name "Reply-To" -value "you@example.com"
</pre>

**Comment by RNalivaika** [comment]
Thanks for your comment. I was able to solve this by specifying Return-Path on the smtp server.
