### ISSUE TITLE
mailsend-go uses in raspberry pi

### ISSUE THREAD

**Issue by ck932** [muquit/mailsend-go#4]
pi@kowloon33:~ $ sudo dpkg -i mailsend-go_linux_64-bit.deb 
dpkg: error processing archive mailsend-go_linux_64-bit.deb (--install):
 package architecture (amd64) does not match system (armhf)
Errors were encountered while processing:
 mailsend-go_linux_64-bit.deb

Thanks

**Comment by muquit** [comment]
Linux version is for AMD64. For the pi, it has to be compiled for ARM. I will make a version available for ARM.
Thanks.

**Comment by ck932** [comment]
thanks a lot

**Comment by muquit** [comment]
I will try to build and test for my pi 3 b+ over the weekends. In the mean time if you have go installed, you can give it a shot yourself. Fetch the mailsend-go source and inside mailsend-go dir, do:

GOOS=linux GOARCH=arm GOARM=5 go build

**Comment by muquit** [comment]
I uploaded a compiled binary for raspberry pi. Please close the bug if it works for you.
Thanks.
