### ISSUE TITLE
Send emails without SMTP authentication

### ISSUE THREAD

**Issue by DMJ-3000** [muquit/mailsend-go#47]
How is it possible to use mailsend-go with an SMTP server which does not require authentication and uses STARTTLS encryption?

**Comment by muquit** [comment]
Sure, as long as your server does not require authentication, just don't specify username and password with auth command.

**Comment by DMJ-3000** [comment]
I've tried several syntaxes, but none seems to work. Would be required an option to specify not to authenticate.
The SMTP server accepts both authentication or not with STARTTLS encryption, if you are inside the LAN. Cecked with Mozilla Thunderbird.

```
mailsend-go.exe -smtp [smtpserver] -t [recipient] -f [sender] -sub "[subject]" body -msg "[message]" auth -user '' -pass ''
ERROR: 535 5.7.8 Error: authentication failed: authentication failure

mailsend-go.exe -smtp [smtpserver] -t [recipient] -f [sender] -sub "[subject]" body -msg "[message]" auth -user "" -pass ""
ERROR: No auth username specified with -user with command auth

mailsend-go.exe -smtp [smtpserver] -t [recipient] -f [sender] -sub "[subject]" body -msg "[message]" auth -user -pass
ERROR: No auth password specified with -pass or env variable SMTP_USER_PASS for command auth

mailsend-go.exe -smtp [smtpserver] -t [recipient] -f [sender] -sub "[subject]" body -msg "[message]" auth
ERROR: No auth username specified with -user with command auth

mailsend-go.exe -smtp [smtpserver] -t [recipient] -f [sender] -sub "[subject]" body -msg "[message]" 
ERROR: gomail: could not send email 1: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname
```

**Comment by DMJ-3000** [comment]
So like the last test.
`mailsend-go.exe -smtp [smtpserver] -t [recipient] -f [sender] -sub "[subject]" body -msg "[message]" `

But how can I solve the issue?
`ERROR: gomail: could not send email 1: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname`

Thanks.

**Comment by muquit** [comment]
What kind of system is it? It appears your SMTP server does not like localhost in HELO command. mailsend-go has a -domain option to specify for HELO. But may be there is a way to disable the check all together in your SMTP server.

**Comment by DMJ-3000** [comment]
Solved adding -domain option equal to -smtp option.

`mailsend-go.exe -smtp [smtpserver] -domain [smtpserver] -t [recipient] -f [sender] -sub "[subject]" body -msg "[message]" `

Thanks a lot.

**Comment by muquit** [comment]
cool
