### ISSUE TITLE
Need for log-file option

### ISSUE THREAD

**Issue by messireL** [muquit/mailsend-go#5]
Please, add the log-file option to be sure all the emails has been send succesfully or to be able to find an error.
Thnx.

**Comment by pswmauro** [comment]
I need too. I used old mailsend on my scripts with -log option (to trace error on unattended systems). I'm trying to use your fantastic new mailsend-go but without this option migrating is impossible.

**Comment by muquit** [comment]
I will add this feature as soon as get some time. It's a work in progress.

**Comment by muquit** [comment]
By the way `develop` branch has `-log filePath` feature.  I will make a release after some testing.

**Comment by muquit** [comment]
Added -log <file> option in v1.0.5
