### ISSUE TITLE
Cannot install on Mac

### ISSUE THREAD

**Issue by kinglok** [muquit/mailsend-go#54]
mailsend-go cannot be installed via brew.

% brew tap muquit/mailsend-go https://github.com/muquit/mailsend-go.git
% brew install mailsend-go                                             
Error: mailsend-go: wrong number of arguments (given 1, expected 0)

**Comment by muquit** [comment]
The original brew formula was created by GoReleaser and seems to be having this issue. So I created the formula by hand now. Please do the following:
```
brew tap
brew untap muquit/mailsend-go
brew tap muquit/mailsend-go
brew install mailsend-go
```

That worked for me. Please give your feedback.

Thanks!

**Comment by kinglok** [comment]
It works for me. Thanks!

**Comment by muquit** [comment]
Updated document
