### ISSUE TITLE
Option -t or -list

### ISSUE THREAD

**Issue by messireL** [muquit/mailsend-go#6]
When I use the -list option -t option doesn't work. I checked it using list-file with addresses. Than -t hasn't been used, but -list is ok.
By the way, how it's possible to comment an address in address-list file? I used # and ; but no result. It'll be usefull to have an opportunity for commenting if it needs to stop mailng to <some> address<es> temporary.
Thnx.

**Comment by Bilbo47** [comment]
Please restore and complete the -tname parameter for when -list is not needed.
